from random import randint

def random_planet():
    planets = [
        'Tatooine',
        'Alderaan',
        'Yavin IV',
        'Hoth',
        'Dagobah',
        'Bespin',
        'Endor',
        'Naboo',
        'Coruscant',
        'Kamino',
        'Geonosis',
        'Utapau',
        'Mustafar',
        'Kashyyyk',
        'Polis Massa',
        'Mygeeto',
        'Felucia',
        'Cato Neimoidia',
        'Saleucami',
        'Stewjon',
        'Eriadu',
        'Corellia',
        'Rodia',
        'Nal Hutta',
        'Dantooine',
        'Bestine IV',
        'Ord Mantell',
        'unknown',
        'Trandosha',
        'Socorro',
        'Mon Cala',
        'Chandrila',
        'Sullust',
        'Toydaria',
        'Malastare',
        'Dathomir',
        'Ryloth',
        'Aleen Minor',
        'Vulpter',
        'Troiken',
        'Tund',
        'Haruun Kal',
        'Cerea',
        'Glee Anselm',
        'Iridonia',
        'Tholoth',
        'Iktotch',
        'Quermia',
        'Dorin',
        'Champala',
        'Mirial',
        'Serenno',
        'Concord Dawn',
        'Zolan',
        'Ojom',
        'Skako',
        'Muunilinst',
        'Shili',
        'Kalee'
    ]

    return planets[randint(1,len(planets)-1)]
